volumes:
  zilean_data:

services:
  zilean:
    image: ipromknight/zilean:latest
    restart: unless-stopped
    environment:
      PUID: 1000
      PGID: 1000
    user: "${PUID}:${PGID}"
    ports:
      - "8181:8181"
    volumes:
      - zilean_data:/app/data