volumes:
  zilean_data:
  elastic_data:

services:
  zilean:
    image: ipromknight/zilean:latest
    restart: unless-stopped
    ports:
      - "8181:8181"
    volumes:
      - zilean_data:/app/data
    environment:
        - ZILEAN__ELASTICSEARCH__URL=http://elasticsearch:9200
    depends_on:
      elasticsearch:
        condition: service_healthy

  elasticsearch:
    image: elasticsearch:8.14.1@sha256:ff3998ab3d8a84984e5298d33d01a174fc5f8abed15ad58d0a54364fc63d68d9
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"
    healthcheck:
      test: curl -s http://localhost:9200 >/dev/null || exit 1
      interval: 30s
      timeout: 10s
      retries: 10
    volumes:
      - elastic_data:/usr/share/elasticsearch/data:rw
    deploy:
      resources:
        limits:
          cpus: '1.00'
          memory: 1024M
        reservations:
          cpus: '0.25'
          memory: 200M
